### ISSUE TITLE
Stuck in loop

### ISSUE THREAD

**Issue by forstjiri** [CNG/ForecastTools#3]
Im stuck on this loop:

``` php
  while ($runningHandles && $execReturnValue == CURLM_OK) {
        $numberReady = curl_multi_select($mh);
        if ($numberReady != -1) {
          do {
            $execReturnValue = c;url_multi_exec($mh, $runningHandles);
          } while ($execReturnValue == CURLM_CALL_MULTI_PERFORM);
        }
      }
```

$execReturnValue is still equal to CURLM_OK, i have CURL installed.

**Comment by CNG** [comment]
I finally had occasion to look into this. You're right, I found a server that had the same problem you saw. I resolved it a bit differently. See this commit: 

https://github.com/CNG/ForecastTools/commit/d430e454c106da70d4d813fabdc9b548c8c0b739

Thank you for reporting!
